---
title: "First Knit"
author: "Isabela Bercian"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I was in a homeschool program called Gorman Learning Center. I graduated in 2022. Math is very, very hard for me. I'm better at English. My strongest subject is English. I enjoy it a lot.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I use an Apple Macbook. I am a total dummy when it comes to computers and technology. I'd rate myself at about a 2. I have internet access at home. However, it can be very slow at times.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I don't mind being called by my name. My friends and family call me Beya. Either one of those is fine.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 I want to become either a lawyer or a college counselor/advisor. I'm majoring in political science, and its of greatest interest to me. Right now I am pursuing an associates degree in political science and I plan on getting my bachelores degree as well.  




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  I've only been to Mexico. In the future, I hope to travel to Australia, Egypt, and Brazil in the future. I've never been in the military. If I were to be drafter, I waould choose to be in the Airforce. I've heard that they're spoiled.




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




